version: "3.8"
networks:
  kafka_network:
    name: cryptoKafkaNetwork
services: 
  cryptokafkastreamer:
    build:  
      context: ./
      dockerfile: dockerfile
    stdin_open: true
    tty: true
    environment:
      KAFKA_CONNECTION: kafka:9092
    networks:
      - kafka_network